server:
  port: 8004
spring:
  application:
    name: edu-course-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu_course?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 47.99.40.74
    port: 6379
    password: Weiwei@5186991
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
